usr/include
usr/lib/*/libkcarchiver.so
usr/lib/*/libkcarchivercore.so
usr/lib/*/libkcfreebusy.so
usr/lib/*/libkchl.so
usr/lib/*/libkcicalmapi.so
usr/lib/*/libkcinetmapi.so
usr/lib/*/libkcmapi.so
usr/lib/*/libkcpyconv.so
usr/lib/*/libkcpydirector.so
usr/lib/*/libkcserver.so
usr/lib/*/libkcservice.so
usr/lib/*/libkcsoapclient.so
usr/lib/*/libkcsoapserver.so
usr/lib/*/libkcssl.so
usr/lib/*/libkcsync.so
usr/lib/*/libkcutil.so
usr/lib/*/libmapi.so

# the following libraries maybe need some adjustment
# done by kopano-server
#usr/lib/*/kopano/dbplugin.so
#usr/lib/*/kopano/ldapplugin.so

# done by kopano-libs
#usr/lib/*/kopano/libkcclient.so

# done by kopano-contacts
#usr/lib/*/kopano/libkccontacts.so

# done by kopano-server
#usr/lib/*/kopano/unixplugin.so

usr/lib/*/pkgconfig/kopano.pc
usr/share/gdb
