etc/kopano/search.cfg
etc/kopano/searchscripts
usr/lib/python3/dist-packages/kopano_search/*.py
usr/lib/python3/dist-packages/kopano_search-*.egg-info/
usr/lib/systemd/system/kopano-search.service  lib/systemd/system/
usr/sbin/kopano-search
#usr/sbin/kopano-search-xapian-compact.py
usr/share/man/man5/kopano-search.cfg.5
usr/share/man/man8/kopano-search.8
debian/apparmor/usr.sbin.kopano-search etc/apparmor.d
