etc/kopano/autorespond
etc/kopano/dagent.cfg
usr/lib/python*/*/kopano_utils
usr/sbin/kopano-autorespond
usr/sbin/kopano-dagent
usr/sbin/kopano-mr-accept
usr/sbin/kopano-mr-process
usr/share/man/man5/kopano-dagent.cfg.5
usr/share/man/man8/kopano-autorespond.8
usr/share/man/man8/kopano-dagent.8
usr/share/man/man8/kopano-mr-accept.8
usr/share/man/man8/kopano-mr-process.8
usr/share/kopano-dagent/python/
usr/share/kopano-dagent/python/plugins/
var/lib/kopano/dagent/plugins/
debian/apparmor/usr.sbin.kopano-dagent etc/apparmor.d
