usr/bin/zarafa-fsck
usr/bin/zarafa-passwd
usr/bin/zarafa-set-oof
usr/bin/zarafa-stats
usr/sbin/zarafa-admin
usr/sbin/zarafa-mailbox-permissions
usr/share/man/man1/zarafa-fsck.1
usr/share/man/man1/zarafa-passwd.1
usr/share/man/man1/zarafa-set-oof.1
usr/share/man/man1/zarafa-stats.1
usr/share/man/man8/zarafa-admin.8
usr/share/man/man8/zarafa-mailbox-permissions.8
etc/bash_completion.d/zarafa-bash-completion.sh usr/share/bash-completion/completions/zarafa
